### PR TITLE
jQuery: edit 2024 README and add April 2024 update

### PR DESCRIPTION
**Pull request by timmywil**
Added note about carryover funds to 2024 README.

### CODE REVIEW

**Comment by timmywil** [comment]
This PR now includes the update for April 2024

**Review by bensternthal — COMMENTED** [review]
The changes look good to me. One thing we should check on.. since we are not officially part of the AO 2024 cohort, do they still want us to provide these types of updates?

**Comment by timmywil** [comment]
I was wondering that as well, but I still get emails/requests to submit updates. Yesterday, I got one from Michelle Martineau.

**Review by Krinkle — APPROVED** [review]
* clarify that jQuery Color is the project completed this month.
* clarify around TestSwarm, to avoid implying it runs on the Jenkins server (it doesn't).
* remove mention of a Jenkins database (there is no separate database running there).
* discovery for jquery-detect source.
* clarify that gzip was already enabled at origin.

**Comment by bensternthal** [comment]
@timmywil ill double check with her and let you know.

**Pull request merged**
